[package]
name    = "feral-setupd"
version = "0.1.0"
edition = "2024"

[dependencies]
bluer         = { version = "0.17.3", features = ["bluetoothd"] }
tokio         = { version = "1.45.0", features = ["full"] }
uuid          = "1.16.0"
futures-util  = "0.3"
dbus          = "0.9"