/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef __GATT_INTERFACES_H__
#define __GATT_INTERFACES_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.bluez.GattService1 */

#define TYPE_GATT_SERVICE1 (gatt_service1_get_type ())
#define GATT_SERVICE1(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_GATT_SERVICE1, GattService1))
#define IS_GATT_SERVICE1(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_GATT_SERVICE1))
#define GATT_SERVICE1_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_GATT_SERVICE1, GattService1Iface))

struct _GattService1;
typedef struct _GattService1 GattService1;
typedef struct _GattService1Iface GattService1Iface;

struct _GattService1Iface
{
  GTypeInterface parent_iface;

  gboolean  (*get_primary) (GattService1 *object);

  const gchar * (*get_uuid) (GattService1 *object);

};

GType gatt_service1_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *gatt_service1_interface_info (void);
guint gatt_service1_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus property accessors: */
const gchar *gatt_service1_get_uuid (GattService1 *object);
gchar *gatt_service1_dup_uuid (GattService1 *object);
void gatt_service1_set_uuid (GattService1 *object, const gchar *value);

gboolean gatt_service1_get_primary (GattService1 *object);
void gatt_service1_set_primary (GattService1 *object, gboolean value);


/* ---- */

#define TYPE_GATT_SERVICE1_PROXY (gatt_service1_proxy_get_type ())
#define GATT_SERVICE1_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_GATT_SERVICE1_PROXY, GattService1Proxy))
#define GATT_SERVICE1_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_GATT_SERVICE1_PROXY, GattService1ProxyClass))
#define GATT_SERVICE1_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_GATT_SERVICE1_PROXY, GattService1ProxyClass))
#define IS_GATT_SERVICE1_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_GATT_SERVICE1_PROXY))
#define IS_GATT_SERVICE1_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_GATT_SERVICE1_PROXY))

typedef struct _GattService1Proxy GattService1Proxy;
typedef struct _GattService1ProxyClass GattService1ProxyClass;
typedef struct _GattService1ProxyPrivate GattService1ProxyPrivate;

struct _GattService1Proxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  GattService1ProxyPrivate *priv;
};

struct _GattService1ProxyClass
{
  GDBusProxyClass parent_class;
};

GType gatt_service1_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GattService1Proxy, g_object_unref)
#endif

void gatt_service1_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
GattService1 *gatt_service1_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
GattService1 *gatt_service1_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void gatt_service1_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
GattService1 *gatt_service1_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
GattService1 *gatt_service1_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_GATT_SERVICE1_SKELETON (gatt_service1_skeleton_get_type ())
#define GATT_SERVICE1_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_GATT_SERVICE1_SKELETON, GattService1Skeleton))
#define GATT_SERVICE1_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_GATT_SERVICE1_SKELETON, GattService1SkeletonClass))
#define GATT_SERVICE1_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_GATT_SERVICE1_SKELETON, GattService1SkeletonClass))
#define IS_GATT_SERVICE1_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_GATT_SERVICE1_SKELETON))
#define IS_GATT_SERVICE1_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_GATT_SERVICE1_SKELETON))

typedef struct _GattService1Skeleton GattService1Skeleton;
typedef struct _GattService1SkeletonClass GattService1SkeletonClass;
typedef struct _GattService1SkeletonPrivate GattService1SkeletonPrivate;

struct _GattService1Skeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  GattService1SkeletonPrivate *priv;
};

struct _GattService1SkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType gatt_service1_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GattService1Skeleton, g_object_unref)
#endif

GattService1 *gatt_service1_skeleton_new (void);


/* ------------------------------------------------------------------------ */
/* Declarations for org.bluez.GattCharacteristic1 */

#define TYPE_GATT_CHARACTERISTIC1 (gatt_characteristic1_get_type ())
#define GATT_CHARACTERISTIC1(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_GATT_CHARACTERISTIC1, GattCharacteristic1))
#define IS_GATT_CHARACTERISTIC1(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_GATT_CHARACTERISTIC1))
#define GATT_CHARACTERISTIC1_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_GATT_CHARACTERISTIC1, GattCharacteristic1Iface))

struct _GattCharacteristic1;
typedef struct _GattCharacteristic1 GattCharacteristic1;
typedef struct _GattCharacteristic1Iface GattCharacteristic1Iface;

struct _GattCharacteristic1Iface
{
  GTypeInterface parent_iface;


  gboolean (*handle_write_value) (
    GattCharacteristic1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_value,
    GVariant *arg_options);

  const gchar *const * (*get_flags) (GattCharacteristic1 *object);

  const gchar * (*get_service) (GattCharacteristic1 *object);

  const gchar * (*get_uuid) (GattCharacteristic1 *object);

};

GType gatt_characteristic1_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *gatt_characteristic1_interface_info (void);
guint gatt_characteristic1_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void gatt_characteristic1_complete_write_value (
    GattCharacteristic1 *object,
    GDBusMethodInvocation *invocation);



/* D-Bus method calls: */
void gatt_characteristic1_call_write_value (
    GattCharacteristic1 *proxy,
    const gchar *arg_value,
    GVariant *arg_options,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean gatt_characteristic1_call_write_value_finish (
    GattCharacteristic1 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean gatt_characteristic1_call_write_value_sync (
    GattCharacteristic1 *proxy,
    const gchar *arg_value,
    GVariant *arg_options,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
const gchar *gatt_characteristic1_get_uuid (GattCharacteristic1 *object);
gchar *gatt_characteristic1_dup_uuid (GattCharacteristic1 *object);
void gatt_characteristic1_set_uuid (GattCharacteristic1 *object, const gchar *value);

const gchar *gatt_characteristic1_get_service (GattCharacteristic1 *object);
gchar *gatt_characteristic1_dup_service (GattCharacteristic1 *object);
void gatt_characteristic1_set_service (GattCharacteristic1 *object, const gchar *value);

const gchar *const *gatt_characteristic1_get_flags (GattCharacteristic1 *object);
gchar **gatt_characteristic1_dup_flags (GattCharacteristic1 *object);
void gatt_characteristic1_set_flags (GattCharacteristic1 *object, const gchar *const *value);


/* ---- */

#define TYPE_GATT_CHARACTERISTIC1_PROXY (gatt_characteristic1_proxy_get_type ())
#define GATT_CHARACTERISTIC1_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_GATT_CHARACTERISTIC1_PROXY, GattCharacteristic1Proxy))
#define GATT_CHARACTERISTIC1_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_GATT_CHARACTERISTIC1_PROXY, GattCharacteristic1ProxyClass))
#define GATT_CHARACTERISTIC1_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_GATT_CHARACTERISTIC1_PROXY, GattCharacteristic1ProxyClass))
#define IS_GATT_CHARACTERISTIC1_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_GATT_CHARACTERISTIC1_PROXY))
#define IS_GATT_CHARACTERISTIC1_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_GATT_CHARACTERISTIC1_PROXY))

typedef struct _GattCharacteristic1Proxy GattCharacteristic1Proxy;
typedef struct _GattCharacteristic1ProxyClass GattCharacteristic1ProxyClass;
typedef struct _GattCharacteristic1ProxyPrivate GattCharacteristic1ProxyPrivate;

struct _GattCharacteristic1Proxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  GattCharacteristic1ProxyPrivate *priv;
};

struct _GattCharacteristic1ProxyClass
{
  GDBusProxyClass parent_class;
};

GType gatt_characteristic1_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GattCharacteristic1Proxy, g_object_unref)
#endif

void gatt_characteristic1_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
GattCharacteristic1 *gatt_characteristic1_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
GattCharacteristic1 *gatt_characteristic1_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void gatt_characteristic1_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
GattCharacteristic1 *gatt_characteristic1_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
GattCharacteristic1 *gatt_characteristic1_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_GATT_CHARACTERISTIC1_SKELETON (gatt_characteristic1_skeleton_get_type ())
#define GATT_CHARACTERISTIC1_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_GATT_CHARACTERISTIC1_SKELETON, GattCharacteristic1Skeleton))
#define GATT_CHARACTERISTIC1_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_GATT_CHARACTERISTIC1_SKELETON, GattCharacteristic1SkeletonClass))
#define GATT_CHARACTERISTIC1_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_GATT_CHARACTERISTIC1_SKELETON, GattCharacteristic1SkeletonClass))
#define IS_GATT_CHARACTERISTIC1_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_GATT_CHARACTERISTIC1_SKELETON))
#define IS_GATT_CHARACTERISTIC1_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_GATT_CHARACTERISTIC1_SKELETON))

typedef struct _GattCharacteristic1Skeleton GattCharacteristic1Skeleton;
typedef struct _GattCharacteristic1SkeletonClass GattCharacteristic1SkeletonClass;
typedef struct _GattCharacteristic1SkeletonPrivate GattCharacteristic1SkeletonPrivate;

struct _GattCharacteristic1Skeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  GattCharacteristic1SkeletonPrivate *priv;
};

struct _GattCharacteristic1SkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType gatt_characteristic1_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GattCharacteristic1Skeleton, g_object_unref)
#endif

GattCharacteristic1 *gatt_characteristic1_skeleton_new (void);


G_END_DECLS

#endif /* __GATT_INTERFACES_H__ */
