name: Build Pacman Package

on:
  workflow_call:
    inputs:
      component:
        description: 'Component to build'
        required: true
        type: string
      version:
        description: 'Package version'
        required: false
        type: string
      description:
        description: 'Package description'
        required: false
        type: string
        default: 'Go application packaged for Arch Linux'
      maintainer:
        description: 'Package maintainer'
        required: false
        type: string
        default: 'GitHub Actions'
  
  workflow_dispatch:
    inputs:
      component:
        description: 'Component to build'
        required: true
        type: choice
        options:
          - feral-connectd
          - feral-setupd
          - feral-state
          - feral-watchdog
          - launcher-ui
      version:
        description: 'Package version (leave empty to use commit hash)'
        required: false
        type: string

jobs:
  build-pacman:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm go git base-devel shadow

      - name: Set Version
        id: set-version
        run: |
          if [ -z "${{ inputs.version }}" ]; then
            VERSION="${{ github.sha }}"
          else
            VERSION="${{ inputs.version }}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Prepare source tarball & PKGBUILD
        working-directory: components/${{ inputs.component }}
        run: |
          set -e
          COMP=${{ inputs.component }}
          VER=${VERSION}

          # 1) Package everything as a .tar.gz, but exclude the archive file itself
          tar czf "${COMP}-${VER}.tar.gz" --exclude="${COMP}-${VER}.tar.gz" .

          # 2) Emit a clean PKGBUILD
          cat <<EOF > PKGBUILD
          # Maintainer: ${{ inputs.maintainer }}
          pkgname=${COMP}
          pkgver=${VER}
          pkgrel=1
          pkgdesc="${{ inputs.description }}"
          arch=('x86_64' 'aarch64')
          url="https://github.com/${{ github.repository }}"
          license=('MIT')
          depends=()
          makedepends=('go')
          options=(!strip)

          source=("${COMP}-${VER}.tar.gz")
          sha256sums=('SKIP')

          build() {
            cd "\$srcdir"
            go build -v -o "\$pkgname"
          }

          package() {
            install -Dm755 "\$srcsrc/\$pkgname" "\$pkgdir/usr/bin/\$pkgname"
          }
          EOF

      - name: Build Pacman Package
        working-directory: components/${{ inputs.component }}
        run: |
          # run makepkg as non-root
          useradd -m builder
          chown -R builder:builder .
          su builder -c "makepkg -f --skipinteg"

      - name: Upload Pacman Package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.component }}
          path: components/${{ inputs.component }}/*.pkg.tar.zst
          retention-days: 7

      - name: Package Info
        run: |
          echo "Component ${{ inputs.component }} version ${{ env.VERSION }} built successfully"