name: Build Feral File Device Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
        default: '0.0.1'

jobs:
  # --- STEP 1: Reuse Build App Job ---
  build-app:
    name: Build Feral File Launcher App
    uses: ./.github/workflows/build-app.yml
    with:
      version: ${{ github.event.inputs.version }}

  # --- STEP 2: Build Raspberry Pi Image ---
  build-image:
    name: Generate Raspberry Pi OS Image
    runs-on: ['self-hosted', 'ARM64']
    needs: build-app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Feral File Launcher App
        uses: actions/download-artifact@v3
        with:
          name: feralfile-launcher-deb
          path: ./custom-stage/packages

      - name: Remame the package
        run: |
          # Rename downloaded package
          mv ./custom-stage/packages/feralfile-launcher_${{ github.event.inputs.version }}_arm64.deb ./custom-stage/packages/feralfile-launcher_arm64.deb

      - name: Build Pi OS Image with pi-gen-action
        uses: usimd/pi-gen-action@v1
        with:
          image-name: feralfile-device-${{ github.event.inputs.version }}
          stage-list: stage0 stage1 stage2 ./custom-stage
          compression: zip
          compression-level: 6
          username: feralfile
          password: feralfile
          hostname: FeralFileDevice
          locale: en_US.UTF-8
          keyboard-keymap: us
          keyboard-layout: English (US)
          release: bookworm
          enable-ssh: 1
          disable-first-boot-user-rename: 1
          export-last-stage-only: true
          wpa-country: 'US'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          verbose-output: true

      - name: Upload Final Image to Artifact
        uses: actions/upload-artifact@v3
        with:
          name: feralfile-device-image
          path: pi-gen/deploy/*.zip

      - name: Cleanup Docker Containers
        if: always()
        run: docker rm -v pigen_work