name: Build Pacman Package

on:
  workflow_call:
    inputs:
      component:
        description: 'Component to build'
        required: true
        type: string
      version:
        description: 'Package version'
        required: false
        type: string
      description:
        description: 'Package description'
        required: false
        type: string
        default: 'Go application packaged for Arch Linux'
      maintainer:
        description: 'Package maintainer'
        required: false
        type: string
        default: 'GitHub Actions'
  
  workflow_dispatch:
    inputs:
      component:
        description: 'Component to build'
        required: true
        type: choice
        options:
          - feral-connectd
          - feral-setupd
          - feral-state
          - feral-watchdog
          - launcher-ui
      version:
        description: 'Package version (leave empty to use commit hash)'
        required: false
        type: string

jobs:
  build-pacman:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm go git base-devel

      - name: Set Version
        id: set-version
        run: |
          if [ -z "${{ inputs.version }}" ]; then
            VERSION="${{ github.sha }}"
          else
            VERSION="${{ inputs.version }}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Go Program
        working-directory: components/${{ inputs.component }}
        run: |
          go build -v -o ${{ inputs.component }}

      - name: Create PKGBUILD
        working-directory: components/${{ inputs.component }}
        run: |
          cat > PKGBUILD << EOF
          # Maintainer: Feral File Device Team <support@feralfile.com>
          
          pkgname=${{ inputs.component }}
          pkgver=${{ env.VERSION }}
          pkgrel=1
          pkgdesc=""
          arch=('x86_64' 'aarch64')
          url="https://github.com/${{ github.repository }}"
          license=('MIT')
          depends=()
          makedepends=()
          
          package() {
            install -Dm755 "${{ inputs.component }}" "\$pkgdir/usr/bin/${{ inputs.component }}"
          }
          EOF

      - name: Build Pacman Package
        working-directory: components/${{ inputs.component }}
        run: |
          # Create a non-root user for building packages
          useradd -m builder
          chown -R builder:builder .
          # Run makepkg as the non-root user
          su -c "makepkg -f" builder

      - name: Upload Pacman Package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.component }}
          path: components/${{ inputs.component }}/${{ inputs.component }}-${{ env.VERSION }}-*.pkg.tar.zst
          retention-days: 7

      - name: Package Info
        run: |
          echo "Component ${{ inputs.component }} version ${{ env.VERSION }} has been built successfully"
          echo "Artifact has been uploaded with name: ${{ inputs.component }}"
