name: Build FeralFile App

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Application version'
        required: true
        default: '1.0.0'
      architecture:
        description: 'Architecture (amd64, arm64)'
        required: true
        default: 'arm64'

jobs:
  build:
    name: Build and Package App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Install dependencies for C code
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake libbluetooth-dev

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build C library
        run: |
          cd feralfile-bluetooth
          make clean
          make
          # Verify the shared library exists
          ls -l libbluetooth_service.so
          cd ..

      - name: Build Flutter app for Linux
        run: flutter build linux

      - name: Package as Debian .deb
        env:
          APP_NAME: feralfile-launcher
          VERSION: ${{ github.event.inputs.version }}
          ARCH: ${{ github.event.inputs.architecture }}
          DESCRIPTION: "Feral File Connection Assistant"
          MAINTAINER: "Bitmark Inc <support@feralfile.com>"
          INSTALL_DIR: "/opt/${{ env.APP_NAME }}"
        run: |
          # Create package directory structure
          mkdir -p package/DEBIAN
          mkdir -p package$INSTALL_DIR/lib
          
          # Copy Flutter app and C library
          cp -r build/linux/x64/release/bundle/* package$INSTALL_DIR/
          cp feralfile-bluetooth/libbluetooth_service.so package$INSTALL_DIR/lib/
          
          # Create control file with package metadata
          cat <<EOF > package/DEBIAN/control
          Package: $APP_NAME
          Version: $VERSION
          Section: base
          Priority: optional
          Architecture: $ARCH
          Maintainer: $MAINTAINER
          Description: $DESCRIPTION
          EOF
          
          # Set permissions
          chmod -R 755 package$INSTALL_DIR
          
          # Build the .deb package
          dpkg-deb --build package ${APP_NAME}_${VERSION}_${ARCH}.deb
          
          # The .deb file will be named feralfile_1.0.0_amd64.deb

      - name: Upload Debian package
        uses: actions/upload-artifact@v3
        with:
          name: feralfile-deb
          path: feralfile_*.deb