name: Build Component

on:
  workflow_call:
    inputs:
      component:
        description: 'Component to build'
        required: true
        type: string
      version:
        description: 'Package version'
        required: false
        type: string
      description:
        description: 'Package description'
        required: false
        type: string
        default: 'Go application packaged for Arch Linux'
      maintainer:
        description: 'Package maintainer'
        required: false
        type: string
        default: 'GitHub Actions'
      build_pacman:
        description: 'Whether to build a pacman package or just the binary'
        required: false
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      component:
        description: 'Component to build'
        required: true
        type: choice
        options:
          - feral-connectd
          - feral-setupd
          - feral-state
          - feral-watchdog
          - launcher-ui
      version:
        description: 'Package version (leave empty to use commit hash)'
        required: false
        type: string
      build_pacman:
        description: 'Whether to build a pacman package or just the binary'
        required: false
        type: boolean
        default: false

jobs:
  build-component:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm go git base-devel shadow

      - name: Set Version
        id: set-version
        run: |
          if [ -z "${{ inputs.version }}" ]; then
            VERSION="${{ github.sha }}"
          else
            VERSION="${{ inputs.version }}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Binary
        working-directory: components/${{ inputs.component }}
        run: |
          go build -v -o "${{ inputs.component }}"
          # Copy any associated service files if they exist
          mkdir -p /tmp/artifact
          cp "${{ inputs.component }}" /tmp/artifact/
          if [ -f "*.service" ]; then
            cp *.service /tmp/artifact/
          fi

      - name: Build Pacman Package
        if: ${{ inputs.build_pacman == true }}
        working-directory: components/${{ inputs.component }}
        run: |
          set -euo pipefail
          COMP=${{ inputs.component }}
          VER=${VERSION}
          TARBALL="${COMP}-${VER}.tar.gz"

          # 1) Create the tarball in /tmp to avoid it being seen mid–archive
          tar czf "/tmp/${TARBALL}" --exclude="${TARBALL}" .

          # 2) Move it back into the component directory
          mv "/tmp/${TARBALL}" .

          # 3) Emit a clean, un-indented PKGBUILD
          cat <<EOF > PKGBUILD
          # Maintainer: ${{ inputs.maintainer }}
          pkgname=${COMP}
          pkgver=${VER}
          pkgrel=1
          pkgdesc="${{ inputs.description }}"
          arch=('x86_64' 'aarch64')
          url="https://github.com/${{ github.repository }}"
          license=('MIT')
          depends=()
          makedepends=('go')
          options=(!strip)

          source=("${TARBALL}")
          sha256sums=('SKIP')

          build() {
            cd "\$srcdir"
            go build -v -o "${COMP}"
          }

          package() {
            install -Dm755 "\$srcdir/${COMP}" "\$pkgdir/usr/bin/${COMP}"
          }
          EOF

          useradd -m builder
          chown -R builder:builder .
          su builder -c "makepkg -f --skipinteg"
          
          # Copy the package to the artifact directory
          cp *.pkg.tar.zst /tmp/artifact/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.component }}
          path: /tmp/artifact
          retention-days: 7

      - name: Component Info
        run: |
          echo "Component ${{ inputs.component }} version ${{ env.VERSION }} built successfully"
          if [ "${{ inputs.build_pacman }}" == "true" ]; then
            echo "Built as pacman package"
          else
            echo "Built as binary only"
          fi