name: Build Arch Linux Image for Radxa X4

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
        default: '0.0.1'
      environment:
        description: "Environment to build"
        required: false
        default: "Production"
        type: choice
        options:
          - Development
          - Production

jobs:
  build-feral-connectd:
    name: Build Feral Connectd
    uses: ./.github/workflows/build-components.yaml
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
      CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
    with:
      component: feral-connectd
      version: ${{ github.event.inputs.version }}
      description: 'Feral File Connectd Service'
      maintainer: 'Feral File'
      build_pacman: true
      
  build-feral-setupd:
    name: Build Feral Setupd
    uses: ./.github/workflows/build-components.yaml
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
      CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
    with:
      component: feral-setupd
      version: ${{ github.event.inputs.version }}
      description: 'Feral File Setup Service'
      maintainer: 'Feral File'
      build_pacman: true

  build-feralfile-pacman-repo:
    name: Build Feralfile pacman repo
    needs: [build-feral-connectd, build-feral-setupd]
    uses: ./.github/workflows/pacman-repo.yaml
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
      CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}

  build-image:
    name: Generate Arch Linux Image for Radxa X4
    runs-on: ubuntu-latest
    needs: [build-feral-connectd, build-feral-setupd, build-feralfile-pacman-repo]
    environment: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'Production' || 'Development') }}

    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download feral-connectd Artifact
        uses: actions/download-artifact@v4
        with:
          name: feral-connectd
          path: /tmp/feral-connectd

      - name: Download feral-setupd Artifact
        uses: actions/download-artifact@v4
        with:
          name: feral-setupd
          path: /tmp/feral-setupd

      - name: Install Build Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm archiso arch-install-scripts dosfstools libisoburn squashfs-tools \
            git curl rclone wget base-devel jq zip unzip fakeroot binutils

      - name: Copy archiso profile
        run: |
          mkdir -p /build
          cp -r archiso-radxa-x4 /build/

      - name: Inject pacman.conf
        run: |
          cat > /build/archiso-radxa-x4/airootfs/etc/pacman.conf << EOF
          [options]
          HoldPkg     = pacman glibc
          Architecture = auto
          Color
          CheckSpace
          ParallelDownloads = 5
          SigLevel    = Required DatabaseOptional
          LocalFileSigLevel = Optional
          ILoveCandy

          [core]
          Include = /etc/pacman.d/mirrorlist

          [extra]
          Include = /etc/pacman.d/mirrorlist

          [community]
          Include = /etc/pacman.d/mirrorlist

          [multilib]
          Include = /etc/pacman.d/mirrorlist

          [feralfile]
          SigLevel = Optional TrustAll
          Server = https://${{ secrets.DISTRIBUTION_AUTH_USER }}:${{ secrets.DISTRIBUTION_AUTH_PASSWORD }}@feralfile-device-distribution.bitmark-development.workers.dev/archlinux/${{ github.ref_name }}/os/\$arch
          EOF

      - name: Copy UI files
        run: |
          mkdir -p /build/archiso-radxa-x4/airootfs/opt/feral/ui/launcher
          cp -r components/launcher-ui/* /build/archiso-radxa-x4/airootfs/opt/feral/ui/launcher/
          mkdir -p /build/archiso-radxa-x4/airootfs/opt/feral/ui/player
          cp -r components/player-wrapper-ui/* /build/archiso-radxa-x4/airootfs/opt/feral/ui/player/
          mkdir -p /build/archiso-radxa-x4/airootfs/home/feralfile/.logs

      - name: Add feral-connectd and feral-setupd Binaries and Services
        run: |
          # Create bin directory if it doesn't exist
          mkdir -p /build/archiso-radxa-x4/airootfs/usr/bin
          
          # Copy the binary
          cp /tmp/feral-connectd/feral-connectd /build/archiso-radxa-x4/airootfs/usr/bin/
          chmod 755 /build/archiso-radxa-x4/airootfs/usr/bin/feral-connectd

          # Copy the binary
          cp /tmp/feral-setupd/feral-setupd /build/archiso-radxa-x4/airootfs/usr/bin/
          chmod 755 /build/archiso-radxa-x4/airootfs/usr/bin/feral-setupd

          # Add connectd config
          mkdir -p /build/archiso-radxa-x4/airootfs/home/feralfile/.config
          cat > /build/archiso-radxa-x4/airootfs/home/feralfile/.config/connectd.json << EOF
          {
            "relayer": {
                "endpoint": "${{ vars.RELAYER_ENDPOINT }}",
                "apiKey": "${{ secrets.RELAYER_API_KEY }}"
            },
            "cdp": {
                "endpoint": "http://127.0.0.1:9222"
            },
            "indexer": {
                "endpoint": "https://indexer.feralfile.com/v2/graphql"
            },
            "feralFile": {
                "endpoint": "https://feralfile.com",
                "assetURL": "https://cdn.feralfileassets.com"
            }
          }
          EOF
          chmod 755 /build/archiso-radxa-x4/airootfs/home/feralfile/.config/connectd.json

      - name: Setup pacman
        run: |
          curl -o /etc/pacman.d/mirrorlist "https://archlinux.org/mirrorlist/?country=US&protocol=https&ip_version=4&use_mirror_status=on"
          sed -i 's/^#Server/Server/' /etc/pacman.d/mirrorlist
          pacman-key --init
          pacman-key --populate archlinux
          pacman -Syy --debug

      - name: Build ISO Image
        run: |
          cd /build
          mkarchiso -v -w /build/work -o /build/out /build/archiso-radxa-x4
          ISO_FILE=$(find /build/out -name "*.iso" | head -n 1)
          if [ -f "$ISO_FILE" ]; then
            NEW_NAME="radxa-x4-arch-${{ github.event.inputs.version }}.iso"
            mv "$ISO_FILE" "/build/out/$NEW_NAME"
            echo "ISO created: /build/out/$NEW_NAME"
          else
            echo "Error: ISO file not found"
            exit 1
          fi

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          cat > ~/.config/rclone/rclone.conf << EOF
          [r2]
          type = s3
          provider = Cloudflare
          access_key_id = ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
          secret_access_key = ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
          endpoint = https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
          acl = private
          no_check_bucket = true
          EOF

      - name: Compress and Upload Image
        run: |
          cd /build/out
          ISO_FILE="radxa-x4-arch-${{ github.event.inputs.version }}.iso"
          zip -j "radxa-x4-arch-${{ github.event.inputs.version }}.zip" "$ISO_FILE"
          rclone copyto "radxa-x4-arch-${{ github.event.inputs.version }}.zip" \
            "r2:${{vars.CLOUDFLARE_R2_BUCKET_NAME}}/${{ github.ref_name }}/radxa-x4-arch-${{ github.event.inputs.version }}.zip" \
            --s3-upload-cutoff=100M \
            --s3-chunk-size=100M \
            --transfers=7 \
            --verbose \
            --stats=1s
          echo "Image successfully uploaded to R2"

      - name: Cleanup
        if: always()
        run: |
          rm -rf /build