name: C Lint

on:
  pull_request:
    paths:
      - '**.c'
      - '**.h'
      - '**/src/**'
      - '**/include/**'

jobs:
  c_lint:
    name: Lint C Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cppcheck
        run: sudo apt-get install -y cppcheck

      - name: Install reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41

      - name: Code review and auto-fix the changed files
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in ${{ steps.changed-files.outputs.changed_files }}; do
            echo "checking: $file"
            if [[ $file == *.c ]] || [[ $file == *.h ]]; then
              # Run cppcheck with detailed output
              cppcheck --enable=all --xml --xml-version=2 $file 2> cppcheck-result.xml
              cat cppcheck-result.xml | reviewdog -f=cppcheck -name=cppcheck -reporter=github-pr-review

              # Run clang-format for auto-fixing
              clang-format -i -style=file $file
            else
              echo "skipping non-C file: $file"
            fi
            codespell -q 3 -w -I .codespellignore --skip "*.svg" $file | reviewdog -efm="%f:%l: %m" -name=codespell -reporter=github-pr-review || true
          done

      - name: suggester / clang-format fixes
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: clang-format
          filter_mode: added
          cleanup: true