name: C Lint

on:
  pull_request:
    paths:
      - 'feralfile-bluetooth/**.c'
      - 'feralfile-bluetooth/**.h'
      - 'feralfile-bluetooth/**.cpp'
      - 'feralfile-bluetooth/**.hpp'
      - 'feralfile-bluetooth/**.cc'

jobs:
  c_lint:
    name: Lint C Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck

      - name: Run cppcheck
        run: |
          cppcheck --enable=all --inconclusive --std=c11 --force feralfile-bluetooth/

      - name: Check for cppcheck issues
        if: failure()
        run: |
          echo "cppcheck found issues in C code."
          exit 1