name: Flutter Lint

on:
  pull_request:
    paths:
      - '**.dart'
      - 'pubspec.yaml'
      - '**/lib/**'
      - '**/test/**'

jobs:
  flutter_lint:
    name: Lint Flutter Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Install dependencies
        run: |
          cd launcher-app
          flutter pub get
        
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41

      - name: Install reviewdog
        uses: reviewdog/action-setup@v1

      - name: Install codespell
        run: pip install codespell

      - name: Code review and auto-fix the changed files
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in ${{ steps.changed-files.outputs.changed_files }}; do
            echo "fixing: $file"
            if [[ $file == *.dart ]]; then
              flutter analyze --no-preamble $file | reviewdog -efm="%p%t%r • %m • %f:%l:%c • %s" -name=flutter-analyze -reporter=github-pr-review
              dart format $file
              dart fix --apply $file
            else
              echo "skipping non-Dart file: $file"
            fi
            codespell -q 3 -w -I .codespellignore --skip "**/*.g.dart,*.svg" $file | reviewdog -efm="%f:%l: %m" -name=codespell -reporter=github-pr-review || true
          done

      - name: suggester / dart fixes
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: dart fix
          filter_mode: added
          cleanup: true