name: Update Pacman Repo DB

on:
  workflow_dispatch:
  workflow_call:

jobs:
  update-repo:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install Required Packages
        run: |
          pacman -Sy --noconfirm rclone pacman-contrib git

      - name: Configure Rclone
        run: |
          mkdir -p ~/.config/rclone
          cat > ~/.config/rclone/rclone.conf << EOF
          [r2]
          type = s3
          provider = Cloudflare
          access_key_id = ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
          secret_access_key = ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
          endpoint = https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
          acl = private
          no_check_bucket = true
          EOF

      - name: Download All Packages
        run: |
          mkdir -p repo/x86_64
          cd repo/x86_64
          rclone copy "r2:${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}/${{ github.ref_name }}/os/x86_64/" . --include "*.pkg.tar.zst" --verbose

      - name: Generate Pacman Database - repo feralfile
        working-directory: repo/x86_64
        run: |
          repo-add feralfile.db.tar.gz *.pkg.tar.zst

      - name: Upload Repo Database
        working-directory: repo/x86_64
        run: |
          rclone copy . \
            "r2:${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}/${{ github.ref_name }}/os/x86_64/" \
            --include "feralfile.db*" \
            --include "feralfile.files*" \
            --s3-upload-cutoff=100M \
            --s3-chunk-size=100M \
            --transfers=3 \
            --verbose \
            --stats=1s